# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  locale: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

ja:
  locale: ja
  contentDir: content/ja
  title: Keiichi Hashimoto
  params:
    description: Keiichi Hashimoto's academic profile.
  menu:
    main:
      - name: 経歴
        url: '#experience'
        weight: 1
      - name: 論文
        url: '#papers'
        weight: 2
      - name: ニュース
        url: '#news'
        weight: 3
